name: Simple Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deployment Step
      run: |
        echo "Deploying the application..."
        # Add your deployment commands here
        # For example, a script to deploy to a server
