name: Simple Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deployment Step
      run: |
        echo "Deploying the application..."
        # Add your deployment commands here

    - name: Create GitHub Deployment
      id: create_deployment
      uses: chrnorm/deployment-action@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: 'production' # Change to your target environment
        ref: ${{ github.ref }}

    - name: Update Deployment Status (in progress)
      if: always()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
        state: 'in_progress'

    # Place any steps here that you want to run as part of your deployment

    - name: Update Deployment Status (success or failure)
      if: always()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        deployment_id: ${{ steps.create_deployment.outputs.deployment_id }}
        state: ${{ job.status }}
    
    - name: Call Webhook on Success
      if: success()
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"success": true, "message": "Deployment completed successfully."}' https://demo-chrisg.tasktop.net/api/v1/artifacts/payload-from-github-deploy/4367c121-c0fb-4e9a-b613-e4d02fe5b326

        
